### ISSUE TITLE
Linux and getch()

### ISSUE THREAD

**Issue by tuh37046** [gmbows/asio-twt#1]
We are using getch() (from conio.h on Windows) to take input from the user. Linux has an implementation of getch() in the curses library (curses.h), but it can be buggy and requires some initialization.  We can use define statements to initialize the library at runtime, but the functionality is still slightly different than the Windows compiled executable.  We should find a way to fix the input system on Linux whether we continue using getch() or not.

**Comment by gmbows** [comment]
Fixed 6/23
